Port 9402 port api search identifier
port-labs/port-k8s-exporter pull request #79
Opened 2024-08-19 18:17 UTC by talsabagport

# Description

What - Add support for search identifier feature
Why - Allows you to update entity without knowing its identifier
How - Refactor the code to allow run initial sync independently, which then can be used to evaluate and keep the identifiers while running initial sync to Port. The identifiers needed for the delete stale entities process at the end of the initial resync.

## Type of change

Please leave one option from the following and delete the rest:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Non-breaking change (fix of existing functionality that will not change current behavior)
- [ ] Documentation (added/updated documentation)

2024-08-25 10:20 UTC, danielsinai requested changes
Great work 🤩

2024-08-25 10:20 UTC, danielsinai commented on pkg/port/entity/entity.go
> +package entity
Why we created a new entity package?
Shouldn't it be under cli?

2024-08-25 10:20 UTC, danielsinai commented on pkg/port/entity/entity.go
> +	}
If none of the above will catch (for example an array / number), we will get an unexpected error, maybe worth adding else and write an error about this type not being support

2024-08-25 10:20 UTC, danielsinai commented on pkg/handlers/controllers_test.go
> +		integrationKinds, err := f.portClient.GetIntegrationKinds(f.controllersHandler.stateKey)
Nice :)

2024-08-25 10:20 UTC, danielsinai commented on pkg/jq/parser.go
> +			if err != nil {
Nice catch!

2024-08-25 10:20 UTC, danielsinai commented on pkg/jq/parser.go
>  				}
May you also add here the else?

2024-08-26 07:34 UTC, omby8888 approved these changes
LGTM

2024-08-26 07:34 UTC, omby8888 commented on pkg/jq/parser_test.go
add a test on search identifier

2024-08-26 12:19 UTC, danielsinai approved these changes

2024-09-01 08:37 UTC, merged